version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo "Deploy started"

      - echo "$EC2_KEY" | tr -d '\r' > key.pem
      - chmod 400 key.pem

      - ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_HOST "
          cd /home/ubuntu/fullstack-cicd-project &&
          git pull --rebase origin main &&
          npm install &&
          pm2 restart all
        "