name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > cicd-key.pem
          chmod 400 cicd-key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i cicd-key.pem ubuntu@52.91.2.130 "
            cd /home/ubuntu/fullstack-cicd-project &&
            git pull --rebase origin main &&
            npm install &&
            pm2 restart all
          "
